import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {

  return (
    <>
      <Head>
        <title>Encore S.</title>
        <meta name="description" content="Encore S. Profile - Generated by Tailwind & React" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
